---
title: "JAN20 DATA ASSESSMENT: annotation part"
author: "Chao"
date: "3/22/2020"
output: 
  html_notebook:
    code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape2)
library(ggplot2)
library(plyr)
library(dplyr)
library(RColorBrewer)
library(configr)
library(tools)
library(stringi)

#functions

#https://www.biostars.org/p/9335/
matcher <- function(pattern, x) {

  ind = gregexpr(pattern, x)[[1]]
  start = as.numeric(ind)
  if(length(start)==1 && start <1){
    return(NA)
  }else{
    end = start + attr(ind, "match.length") - 2
    res <- as.numeric(apply(cbind(start,end), 1, function(y) substr(x, start=y[1], stop=y[2])))
    res[which(is.na(res))] <- 1
    return(res)
  }
}

doone <- function(c, cigar) {
  pat <- paste("\\d*", c , sep="")
  sum(as.numeric(matcher(pat, cigar)), na.rm=T)
}


## takes a cigar string and parses it, not very fast but...
cigarsums <- function(cigar, chars=c("M","N","D","I","S","H", "P", "X", "=")) {
   sapply (chars, doone, cigar)
}


n50 <- function(x){
  x1 <- rev(sort(x))
  cumsum.x1 <- cumsum(x1)
  find.n50 <- which(cumsum.x1 >= sum(x1)/2)
  return(x1[find.n50[1]])
}

md5 <- function(f,m){
  if(tools::md5sum(f)==m){
    warning("MD5 check passed.\n")
    return(f)
  }else{
    stop("MD5 check failed. Please check the version and content!\n")
  }
}

getMapPropFun <- function(d){
  uOrder <- c("ALL","SSU","ITS1","5.8S","ITS2","LSU")
  ulist <- data.frame(key=c("ALL","SSU","16S","ITS","ITS1","5.8S","ITS2","LSU","23S"),
                      ind=c(1,2,2,3,3,4,5,6,6))
  getM <- stri_match_all_regex(d,"(ALL|23S|LSU|ITS|ITS1|ITS2|5.8S|SSU|16S)\\((\\d+)%\\)")
  getN <- length(getM)
  res <- matrix(0,ncol = 6,nrow = getN)
  for(i in 1:length(getM)){
    geti <- getM[[i]]
    for(j in 1:nrow(geti)){
      res[i,ulist$ind[which(ulist$key==geti[j,2])]] <- geti[j,3]
    }
  }
  res <- matrix(as.numeric(res),ncol=6)
  colnames(res) <- uOrder
  return(res)
}
```

# Quantification

cluster same samples' clips to get LOTU:
```{bash}
# merge LOTUs

metabbq IO clade2tree -i SAM/SBR/CLIP/id90def4.clust.fa -s SAM/SBR/CLIP/tt.clade.uc -o SAM/SBR/KRAKEN/BEAD -v

metabbq buildKraken2db.sh SAM/SBR/KRAKEN/BEAD 4

awk -F "\t" '{split($1,a,";");print a[1]"\t"$2}' SAM/SBR/KRAKEN/BEAD/taxonomy/paths.txt > SAM/SBR/KRAKEN/BEAD/data/topRank.map
####
# mapping to merged db
for i in {S,O}{1,2,3,7,8,9};do
ln -s ../../SBR/KRAKEN/BEAD SAM/$i/KRAKEN/BEAD;
done

#use bracken
metabbq smk --config kk2_db="BEAD" -j -npk SAM/{S,O}{1,2,3,7,8,9}/KRAKEN/reads2BEAD.bead.bracken

for i in {S,O}{1,2,3,7,8,9};do 
  awk -v n=$i 'FNR>1{print n"\t"$0}' SAM/$i/KRAKEN/reads2BEAD.bead.bracken;
done > STAT/KRAKEN/SBR.reads2BEAD.bead.S.bracken

for i in {S,O}{1,2,3,7,8,9};do for j in {G,S1,S2,S3};do
  bracken -d SAM/$i/KRAKEN/BEAD -i SAM/$i/KRAKEN/reads2BEAD.bead.kreport2 -l $j -o SAM/$i/KRAKEN/reads2BEAD.bead.$j.bracken -w SAM/$i/KRAKEN/reads2BEAD.bead.$j.breport2 ;
done & done

for j in {G,S1,S2,S3};do for i in {S,O}{1,2,3,7,8,9};do 
  awk -v n=$i 'FNR>1{print n"\t"$0}' SAM/$i/KRAKEN/reads2BEAD.bead.$j.bracken
done > STAT/KRAKEN/SBR.reads2BEAD.bead.$j.bracken & done

#no-barcode
for i in {S,O}{1,2,3,7,8,9};do
  bracken -d SAM/$i/KRAKEN/SBR -i SAM/$i/KRAKEN/reads2BEAD.kreport2 \
  -o SAM/$i/KRAKEN/reads2BEAD.read.bracken -w SAM/$i/KRAKEN/reads2BEAD.read.breport2 &
done

for i in {S,O}{1,2,3,7,8,9};do 
  awk -v n=$i 'FNR>1{print n"\t"$0}' SAM/$i/KRAKEN/reads2BEAD.read.bracken;
done > STAT/KRAKEN/SBR.reads2BEAD.read.bracken

```


### Read Bracken


```{r}
BEAD.topRank.map <- read.table("../../Results/JAN20/SAM/SBR/KRAKEN/BEAD/data/topRank.map",comment.char = "",
                        sep="\t",col.names=c("domain","taxID"))
#rank level: S
SBR.r2BEAD.species.read.bracken <- read.table(
  md5("../../Results/JAN20/STAT/KRAKEN/SBR.reads2BEAD.read.bracken","a7a4d00c66eb152694735a2b444d8478"),
  as.is = T,quote = "",comment.char = "", sep="\t",
  col.names = c("SID","name","taxID","rank","kraken_assigned_reads","added_reads","new_est_reads","fraction_total_reads"))

SBR.r2BEAD.species.bracken <- read.table(
  md5("../../Results/JAN20/STAT/KRAKEN/SBR.reads2BEAD.bead.S.bracken","727630380e66aee2a40da326bde34907"),
  as.is = T,quote = "",comment.char = "", sep="\t",
  col.names = c("SID","name","taxID","rank","kraken_assigned_reads","added_reads","new_est_reads","fraction_total_reads"))
SBR.r2BEAD.species.bracken <- rbind(
  cbind(tech="READ",SBR.r2BEAD.species.read.bracken),
  cbind(tech="BEAD",SBR.r2BEAD.species.bracken)
)
SBR.r2BEAD.species.bracken$UID <- paste0(SBR.r2BEAD.species.bracken$tech,SBR.r2BEAD.species.bracken$SID)
SBR.r2BEAD.species.bracken$SAM <- substr(SBR.r2BEAD.species.bracken$SID,1,1)
SBR.r2BEAD.species.bracken$REP <- substr(SBR.r2BEAD.species.bracken$SID,2,2)
SBR.r2BEAD.species.bracken$LIB <- ifelse(SBR.r2BEAD.species.bracken$REP%in%c(1,2,3),"RCA","NORCA")
SBR.r2BEAD.species.bracken$REP <- as.factor(SBR.r2BEAD.species.bracken$REP)
levels(SBR.r2BEAD.species.bracken$REP) <- c("A","B","C","A","B","C")
SBR.r2BEAD.species.bracken$tax <- sapply(strsplit(as.character(SBR.r2BEAD.species.bracken$name),"__"),"[",2)
SBR.r2BEAD.species.bracken$tax <- reorder(SBR.r2BEAD.species.bracken$tax,SBR.r2BEAD.species.bracken$fraction_total_reads,sum)

SBR.r2BEAD.species.bracken <- ddply(
  SBR.r2BEAD.species.bracken,c("UID"),transform,
  pct.k=kraken_assigned_reads/sum(kraken_assigned_reads),
  pct.a=added_reads/sum(added_reads),
  pct=new_est_reads/sum(new_est_reads))


top20tax <- rev(levels(reorder(SBR.r2BEAD.species.bracken$tax,SBR.r2BEAD.species.bracken$pct,min)))[1:20]

SBR.r2BEAD.species.b.count <- ddply(SBR.r2BEAD.species.bracken,c("UID"),summarise,observed=length(which(new_est_reads>10)))

SBR.r2BEAD.species.bracken$tax20 <- ifelse(
  as.character(SBR.r2BEAD.species.bracken$tax)%in%top20tax,as.character(SBR.r2BEAD.species.bracken$tax),"Others")
SBR.r2BEAD.species.bracken$tax20[which(SBR.r2BEAD.species.bracken$name=="UNCLASSIFIED")] <- "UNCLASSIFIED"

SBR.r2BEAD.species.b.stat <- ddply(SBR.r2BEAD.species.bracken,c("SAM","tech","LIB","SID","UID","tax20"),summarise,pct=sum(pct))
SBR.r2BEAD.species.b.stat$taxOrder <- reorder(SBR.r2BEAD.species.b.stat$tax20,SBR.r2BEAD.species.b.stat$pct,max)

```


```{r}
ggplot(SBR.r2BEAD.species.b.stat,aes(x=taxOrder,y=pct,fill=tech,color=LIB)) + geom_boxplot() + 
  coord_flip() + facet_grid(.~SAM) + scale_y_log10()
ggplot(SBR.r2BEAD.species.b.stat,aes(x=taxOrder,y=pct,fill=UID)) + geom_bar(stat="identity",position="dodge") + coord_flip() + facet_grid(.~SAM) + scale_y_log10()
ggplot(SBR.r2BEAD.species.b.stat,aes(x=UID,y=pct,fill=taxOrder)) + geom_bar(stat="identity",position="fill")
ggplot(SBR.r2BEAD.species.b.stat%>%filter(!tax20%in%c("Others","bacterium")),aes(x=SID,y=pct,fill=taxOrder)) + 
  geom_bar(stat="identity",position="stack") +facet_grid(.~SAM+tech,scale="free")

```


### PCA
```{r}
SBR.r2BEAD.b.sp.more <- merge(SBR.r2BEAD.species.bracken,BEAD.topRank.map,by="taxID",all.x=T)

SBR.sp.count.mtx <- dcast(SBR.r2BEAD.b.sp.more,taxID+domain+name~UID,value.var = "kraken_assigned_reads",fill = 0)
row.kept <- which(apply(SBR.sp.count.mtx[,4:15],1,max)>10)
tax.kept <- SBR.sp.count.mtx$taxID[row.kept]
SBR.sp.prf.mtx <- dcast(SBR.r2BEAD.b.sp.more,taxID+domain+name~UID,value.var = "pct",fill = 0)
rownames(SBR.sp.prf.mtx) <- SBR.sp.prf.mtx$taxID
taxName <- SBR.sp.prf.mtx$name
taxType <- sapply(strsplit(taxName,"__"),"[",1)
SBR.sp.cut.mtx <- SBR.sp.prf.mtx[row.kept,]
SBR.sp.cut.mtx.pca <- prcomp(t(as.matrix(SBR.sp.cut.mtx[,-c(1:3)])),center = T,scale. = T)
summary(SBR.sp.cut.mtx.pca)

SBR.sp.C4.1.mtx <- as.matrix(SBR.sp.cut.mtx[which(SBR.sp.cut.mtx$domain=="CLADE0.4__1"),-c(1:3)])
SBR.sp.C4.1.pca <- prcomp(t(SBR.sp.C4.1.mtx),center = T,scale. = T)
SBR.sp.C4.2.mtx <- as.matrix(SBR.sp.cut.mtx[which(SBR.sp.cut.mtx$domain=="CLADE0.4__2"),-c(1:3)])
SBR.sp.C4.2.pca <- prcomp(t(SBR.sp.C4.1.mtx),center = T,scale. = T)
SBR.sp.C4.3.mtx <- as.matrix(SBR.sp.cut.mtx[which(SBR.sp.cut.mtx$domain=="CLADE0.4__3"),-c(1:3)])
SBR.sp.C4.3.pca <- prcomp(t(SBR.sp.C4.1.mtx),center = T,scale. = T)

SBR.sp.mtx.pca.df <- data.frame(SID=rownames(SBR.sp.cut.mtx.pca$x),SBR.sp.cut.mtx.pca$x)
ggplot(SBR.sp.mtx.pca.df,aes(x=PC1,y=PC2,color=SID)) +geom_point(size=3) + geom_text(aes(label=SID))

group.df <- unique(SBR.r2BEAD.species.bracken[,c("UID","SAM","SID","LIB","tech")])
SBR.sp.multi.pca.df <- merge(group.df,rbind(
  data.frame(type="ALL",SBR.sp.cut.mtx.pca$x[,1:5]),
  data.frame(type="C4.1",SBR.sp.C4.1.pca$x[,1:5]),
  data.frame(type="C4.2",SBR.sp.C4.2.pca$x[,1:5]),
  data.frame(type="C4.3",SBR.sp.C4.3.pca$x[,1:5])
),by.y="row.names",by.x="UID")

ggplot(SBR.sp.multi.pca.df,aes(x=PC1,y=PC2,color=LIB,shape=tech)) +geom_point(size=3) + 
  #scale_shape_manual(values = c(21,22)) +
  geom_text(aes(label=SID),nudge_x = 3,nudge_y = 3) + facet_wrap(~type,ncol=3,scale="free")

```

```{r}
pheatmap(cor(SBR.sp.cut.mtx[,-c(1:3)],method = "s"),display_numbers = T,cluster_rows = F,cluster_cols = F)
pheatmap(cor(SBR.sp.C4.1.mtx,method = "s"),display_numbers = T,cluster_rows = F,cluster_cols = F)
pheatmap(cor(SBR.sp.C4.2.mtx,method = "s"),display_numbers = T,cluster_rows = F,cluster_cols = F)
pheatmap(cor(SBR.sp.C4.3.mtx,method = "s"),display_numbers = T,cluster_rows = F,cluster_cols = F)

```


**QQ plot**
```{r}
SBR.stat.sp.df1s <- dcast(SBR.r2BEAD.b.sp.more%>%filter(taxID%in%tax.kept),SAM+LIB+domain+REP+tax~tech,
                          value.var = "pct",fun.aggregate = sum,fill = 0)
SBR.stat.sp.df1s.cor <- ddply(SBR.stat.sp.df1s,c("SAM","LIB","REP"),summarise, cor=cor(READ,BEAD,method = "s") )
SBR.stat.sp.df1s.cor$corLabel <- paste0("r=",round(SBR.stat.sp.df1s.cor$cor,2))

ggplot(SBR.stat.sp.df1s,aes(x=READ,y=BEAD,color=factor(REP))) +geom_point() +
  geom_abline(intercept = c(-1,0,1),slope=1,linetype=2) + facet_grid(SAM+LIB~REP) +
  geom_text(data=SBR.stat.sp.df1s.cor,aes(x=1e-3,y=0.1,label=corLabel)) +
  scale_x_log10() + scale_y_log10() 

```

```{r}
SBR.stat.sp.df2s <- dcast(SBR.r2BEAD.b.sp.more%>%filter(taxID%in%tax.kept),SAM+tech+domain+REP+tax~LIB,
                          value.var = "pct",fun.aggregate = sum,fill = 0)
SBR.stat.sp.df2s.cor <- ddply(SBR.stat.sp.df2s,c("SAM","tech","REP"),summarise, cor=cor(NORCA,RCA,method = "s") )
SBR.stat.sp.df2s.cor$corLabel <- paste0("r=",round(SBR.stat.sp.df2s.cor$cor,2))

ggplot(SBR.stat.sp.df2s,aes(x=NORCA,y=RCA,color=factor(REP))) +geom_point() +
  geom_abline(intercept = 0,slope=c(0.8,1,1.2),linetype=2) + facet_grid(SAM+tech~REP) +
  geom_text(data=SBR.stat.sp.df2s.cor,aes(x=1e-3,y=0.1,label=corLabel)) +
  scale_x_log10() + scale_y_log10() 

```


```{r}
SBR.stat.sp.df3s <- dcast(SBR.r2BEAD.b.sp.more%>%filter(taxID%in%tax.kept),SAM+tech+LIB+domain+taxID~REP,
                          value.var = "pct",fill = 0,fun.aggregate = sum)

SBR.stat.sp.df3S <- NULL
for(i in 6:8){
  tmp <- SBR.stat.sp.df3s[,-i]
  colnames(tmp)[6:7] <- c("rep1","rep2")
  SBR.stat.sp.df3S <- rbind(SBR.stat.sp.df3S,data.frame(set=colnames(SBR.stat.sp.df3s)[i],tmp))
}
SBR.stat.sp.df3S.cor <- ddply(SBR.stat.sp.df3S,c("SAM","tech","LIB","domain","set"),summarise,cor=cor(rep1,rep2,method="s"))
SBR.stat.sp.df3S.cor$corLabel <- paste0("r=",round(SBR.stat.sp.df3S.cor$cor,2))

ggplot(SBR.stat.sp.df3S,aes(x=rep1,y=rep2,color=factor(LIB))) +geom_point() +
  geom_abline(intercept = 0,slope=c(0.85,1,1.15),linetype=2) + facet_grid(set+LIB~SAM+domain+tech) + 
  geom_text(data=SBR.stat.sp.df3S.cor,aes(x=1e-3,y=0.1,label=corLabel)) +
  scale_x_log10() + scale_y_log10() 
```

```{r}
ddply(SBR.stat.sp.df2s,c("SAM","rep"),summarise,
      sumRCAwith0NoRCA=sum(RCA[which(NoRCA==0)]),
      sumNoRCAwith0RCA=sum(NoRCA[which(RCA==0)]))
```

# old

# observed taxonomies

```{r}
SBCR.rand.tax.count <- read.table(
  md5("../../Results/JAN20/STAT/KRAKEN/SCR.rand.tax.count","83fd7b6030ae999c48cfc6866bc607ea"),
  sep="\t",col.names = c("SID","db","size","rep","count","beads","unclassified"))
levels(SBCR.rand.tax.count$SID)[which(levels(SBCR.rand.tax.count$SID)%in%c("S2","O2"))] <- c("S2","O2")
SBCR.rand.tax.count$SID <- factor(as.character(SBCR.rand.tax.count$SID),levels=paste0(rep(c("O","S"),each=6),rep(seq(1,6),2)))
SBCR.rand.tax.count$SAM <- substr(SBCR.rand.tax.count$SID,1,1)
SBCR.rand.tax.count$SREP <- substr(SBCR.rand.tax.count$SID,2,1)
SBCR.rand.tax.count$KDM <- ifelse(grepl("1|2|3",SBCR.rand.tax.count$SID),"BAC","FUNGI")

ggplot(SBCR.rand.tax.count%>%filter(count>0&db!=""&!is.na(size)),aes(x=size,y=count,color=db,fill=factor(rep))) + 
  geom_line(size=1) + geom_point() + facet_wrap(~SID,ncol=3)
ggplot(SBCR.rand.tax.count%>%filter(count>0),aes(x=size,y=count,color=factor(rep))) + geom_line() + geom_point() + 
  facet_grid(db~SID,scale="free") + scale_x_continuous(breaks = seq(0,2e9,2e7),labels = seq(0,2000,20))

SBCR.rand.tax.count.stat <- ddply(
  SBCR.rand.tax.count%>%filter(count>0&db!=""&!is.na(size)),c("SID","SAM","KDM","db","size"),summarise,sd=sd(count),count=mean(count))

ggplot(SBCR.rand.tax.count.stat,aes(x=factor(size),y=count,fill=db)) + geom_boxplot(width=1) + 
  #geom_hline(data=db.tax.count,aes(yintercept = count,color=kingdom),linetype=2) +
  facet_grid(.~KDM,scale="free") + 
  scale_x_discrete(breaks = seq(0,2e9,2e7),labels = seq(0,2000,20))

ggplot(SBCR.rand.tax.count%>%filter(count>0&db!=""&!is.na(size)),aes(x=size,y=count,color=db)) + 
  geom_line(aes(group=interaction(SID,db,rep)),alpha=.5) + geom_point(aes(shape=SAM)) + 
  facet_grid(KDM~.,scale="free") +theme_bw() + 
  xlab("# reads") + ylab("Observed Species and Unknown OTUs")
```

```{r}
ggplot(SBCR.rand.tax.count%>%filter(count>0&db!=""&!is.na(size)),aes(x=size,y=count,color=SID)) + 
  geom_line(aes(group=interaction(SID,db,rep)),alpha=.5) + geom_point(aes(shape=SAM)) + 
  #geom_smooth() +
  #geom_hline(data=db.tax.count,aes(yintercept = count,color=kingdom),linetype=2) +
  facet_grid(KDM~SREP,scale="free")
```

```{r}
ggplot(SBCR.rand.tax.count,aes(x=size,y=unclassified/beads,color=db)) + 
  geom_line(aes(group=interaction(SID,db,rep)),alpha=.5) + geom_point(aes(shape=SAM)) + 
  facet_grid(SREP~KDM,scale="free")
```

#FIN.