---
title: "JAN20 DATA ASSESSMENT"
author: "Chao"
date: "1/21/2020"
output: 
  html_notebook:
    code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(treeio)
library(ggtree)
library(ggplot2)
```

# Background

Ref:  
1. https://guangchuangyu.github.io/ggtree-book/chapter-ggtree.html  
2. https://yulab-smu.github.io/treedata-book/chapter2.html


**Get subunits sequence**
```{bash, eval=FALSE}
cd $LFR/Assay/15.AUG20

for i in {S,O}{1,2,3};do 
  awk -v n=$i 'FNR%2==1{if(/>16S_rRNA/){gsub("16S_rRNA::",n);p=1}else{p=0}} (p==1){print}' SAM/$i/CLIP/all.barrnap.fa;
done > SAM/SBR/CLIP/all.SSU.fa
for i in {S,O}{1,2,3};do 
  awk -v n=$i 'FNR%2==1{if(/>23S_rRNA/){gsub("23S_rRNA::",n);p=1}else{p=0}} (p==1){print}' SAM/$i/CLIP/all.barrnap.fa;
done > SAM/SBR/CLIP/all.LSU.fa
# or
for i in {S,O}{1,2,3};do 
  awk -v n=$i 'FNR%2==1{gsub(">",">"n)};{print}' SAM/$i/PREDICT/barrnap.ssu.fa;
done > SAM/SBR/PREDICT/barrnap.ssu.fa
for i in {S,O}{1,2,3};do 
  awk -v n=$i 'FNR%2==1{gsub(">",">"n)};{print}' SAM/$i/PREDICT/barrnap.lsu.fa;
done > SAM/SBR/PREDICT/barrnap.lsu.fa
```

Get species level OTUs:
```{bash,eval=FALSE}
metabbq IO tree2fa -s SAM/SBR/PREDICT/barrnap.ssu.fa -l SAM/SBR/PREDICT/barrnap.lsu.fa -r species -d CLADE0.99 -t SAM/SBR/KRAKEN/BEAD/data/added.txt -o SAM/SBR/PREDICT/species.fa -p -v
```
```
[tree2fa] start
  Reading SAM/SBR/CLIP/all.SSU.fa ... done
  Reading SAM/SBR/CLIP/all.LSU.fa ... done
  Reading SAM/SBR/KRAKEN/BEAD/data/added.txt ... done
  Writing to SAM/SBR/PREDICT/species.fa ...done
  Written 24206 clade seqs. 23793 records cannot found seqs.
  SSU: 23599 (875+22687+37) | LSU: 1438(778+56+604) | BOTH:831(207+624+641)
[All done!]
```
Get genus level OTUs:
```{bash,eval=FALSE}
metabbq IO tree2fa -s SAM/SBR/CLIP/all.SSU.fa -l SAM/SBR/CLIP/all.LSU.fa -r genus -d CLADE0.97 -t SAM/SBR/KRAKEN/BEAD/data/added.txt -o SAM/SBR/PREDICT/genus.fa -p -v
```
```
[tree2fa] start
  Reading SAM/SBR/CLIP/all.SSU.fa ... done
  Reading SAM/SBR/CLIP/all.LSU.fa ... done
  Reading SAM/SBR/KRAKEN/BEAD/data/added.txt ... done
  Writing to SAM/SBR/PREDICT/genus.fa ...done
  Written 3105 clade seqs. 10653 records cannot found seqs.
  SSU: 3090 (212+2867+11) | LSU: 199(49+15+135) | BOTH:184(74+110+146)
[All done!]
```

**RUN RAxML **
genus: both subunits joint:
```{bash, eval=FALSE}
mafft --thread 16 SAM/SBR/PREDICT/genus.both.fa > SAM/SBR/PREDICT/genus.both.mafft.fa
trimal -gappyout -in SAM/SBR/PREDICT/genus.ssu.mafft.fa -out SAM/SBR/PREDICT/genus.ssu.mafft.trimal.fa

raxmlHPC-HYBRID-AVX -f a -p 12345 -s SAM/SBR/PREDICT/genus.ssu.mafft.trimal.fa -x 12345 -T 20 -# 20 -m GTRCAT  -w $PWD/SAM/SBR/PREDICT -n genus.ssu.raxml
```

treeio practices:
```{r}
beast_file <- system.file("examples/MCC_FluA_H3.tree", 
                          package="ggtree")
rst_file <- system.file("examples/rst", package="ggtree")
mlc_file <- system.file("examples/mlc", package="ggtree")

beast_tree <- read.beast(beast_file)
codeml_tree <- read.codeml(rst_file, mlc_file)
merged_tree <- merge_tree(beast_tree, codeml_tree)

get.fields(merged_tree)
```
```{r}
library(dplyr)
df <- fortify(merged_tree) %>%
  select(dN_vs_dS, dN, dS, rate) %>%
  subset(dN_vs_dS >=0 & dN_vs_dS <= 1.5) %>%
  tidyr::gather(type, value, dN_vs_dS:dS)
df$type[df$type == 'dN_vs_dS'] <- 'dN/dS'
df$type <- factor(df$type, levels=c("dN/dS", "dN", "dS"))
ggplot(df, aes(rate, value)) + geom_hex() + 
  facet_wrap(~type, scale='free_y') 
```


Read from Raxml:
```{r}
raxml_file <- system.file("extdata/RAxML/",
                          "RAxML_bipartitionsBranchLabels.H3", 
                          package="treeio")
raxml <- read.raxml(raxml_file)
get.fields((raxml))
ggtree(raxml)

```
Time-scaled layout:
```{r}
beast_file <- system.file("examples/MCC_FluA_H3.tree", 
                          package="ggtree")
beast_tree <- read.beast(beast_file)
ggtree(beast_tree, mrsd="2013-01-01") + theme_tree2()
```

Annotation of clade
```{r}
treetext = "(((ADH2:0.1[&&NHX:S=human], ADH1:0.11[&&NHX:S=human]):
0.05 [&&NHX:S=primates:D=Y:B=100],ADHY:
0.1[&&NHX:S=nematode],ADHX:0.12 [&&NHX:S=insect]):
0.1[&&NHX:S=metazoa:D=N],(ADH4:0.09[&&NHX:S=yeast],
ADH3:0.13[&&NHX:S=yeast], ADH2:0.12[&&NHX:S=yeast],
ADH1:0.11[&&NHX:S=yeast]):0.1[&&NHX:S=Fungi])[&&NHX:D=N];"
tree <- read.nhx(textConnection(treetext))
ggtree(tree) + geom_tiplab() + 
  geom_label(aes(x=branch, label=S), fill='lightgreen') + 
  geom_label(aes(label=D), fill='steelblue') + 
  geom_text(aes(label=B), hjust=-.5)
```


```{r}
nwk <- system.file("extdata", "sample.nwk", package="treeio")
tree <- read.tree(nwk)
p <- ggtree(tree) + geom_tiplab()
viewClade(p, MRCA(p, "I", "L"))

```

```{r}
p2 <- p %>% collapse(node=21) + 
  geom_point2(aes(subset=(node==21)), shape=21, size=5, fill='green')
p2 <- collapse(p2, node=23) + 
  geom_point2(aes(subset=(node==23)), shape=23, size=5, fill='red')
print(p2)
expand(p2, node=23) %>% expand(node=21)
```


read real data
```{r}
read.raxml2 <- function (file) 
{
  tree.text <- readLines(file)
  #tree_text <- gsub("(:[0-9\\.eE+\\-]+)\\[(\\d+)\\]", "\\@\\2\\1", tree.text)
  tree_text <- gsub("\\)(\\d+)(:[0-9\\.eE+\\-]+)", "\\)\\@\\1\\2", tree.text)
  phylo <- read.tree(text = tree_text)
  if (any(grepl("@", phylo$node.label))) {
    bootstrap <- as.numeric(gsub("[^@]*@(\\d+)", "\\1", 
      phylo$node.label))
    phylo$node.label <- gsub("@\\d+", "", phylo$node.label)
  }
  if (all(phylo$node.label == "")) {
    phylo$node.label <- NULL
  }
  bootstrap <- data_frame(node = Ntip(phylo) + 1:phylo$Nnode, bootstrap = bootstrap)
  new("treedata", file = file, treetext = tree.text,phylo = phylo, data = bootstrap)
}
phylum.raxml <- read.raxml2("../../Results/JAN20/SAM/SBR/PREDICT/RAxML_bipartitions.phylum+ref.ssu.raxml")
get.fields((phylum.raxml))

p <- ggtree(phylum.raxml) + geom_tiplab() #+ geom_label(aes(label=bootstrap))

p2 <- p %>% collapse(node=65) + 
  geom_point2(aes(subset=(node==65)), shape=21, size=5, fill='green')

p2
```

read external info:
```{r}

path.info <- read.table("../../Results/JAN20/SAM/SBR/KRAKEN/test/data/added.tsv",
       sep="\t",fill = NA,col.names = c("id","rank","clade","anno","SID"),as.is = T)


phylum.raxml <- read.raxml("../../Results/JAN20/SAM/SBR/PREDICT/RAXML/RAxML_bipartitionsBranchLabels.phylum+ref.ssu.raxml")
p.info <- read.table("../../Results/JAN20/SAM/SBR/PREDICT/phylum.SSU.inf",sep="\t",fill=NA,
                     col.names = c("id","cladeName","SID","length","len","clades","annos"))

p.info.df <- as_tibble(merge(data.frame(label=as.phylo(phylum.raxml)$tip.label),
      merge(p.info,path.info,by="id"),by.x="label",by.y="id",all.x=T))
p.info.df$cladeName <- ifelse(is.na(p.info.df$cladeName),as.character(p.info.df$label),p.info.df$cladeName)
p.info.df$anno <- ifelse(is.na(p.info.df$anno)|p.info.df$anno=="",as.character(p.info.df$cladeName),p.info.df$anno)
p.tree <- full_join(phylum.raxml, p.info.df, by="label")

p <- ggtree(p.tree) + geom_tiplab(aes(label=anno))
p

p2 <- p %>% collapse(node=65) + 
  geom_point2(aes(subset=(node==65)), shape=21, size=5, fill='green')

p2
```



test species tree:
```{r}
sp.raxml <- read.raxml2("../../Results/JAN20/SAM/SBR/PREDICT/RAxML_bipartitions.species+ref.ssu.raxml")
sp.info <- read.table("../../Results/JAN20/SAM/SBR/PREDICT/species.SSU.inf",sep="\t",fill = NA,
                     col.names = c("id","SID","length","len","clades","annos"))

sp.info.df <- as_tibble(merge(data.frame(label=as.phylo(sp.raxml)$tip.label),
      merge(sp.info,path.info,by="id"),by.x="label",by.y="id",all.x=T))
sp.info.df$clade <- ifelse(is.na(sp.info.df$clade),as.character(sp.info.df$label),sp.info.df$clade)
sp.info.df$anno <- ifelse(is.na(sp.info.df$anno)|sp.info.df$anno=="",as.character(sp.info.df$clade),sp.info.df$anno)
sp.tree <- full_join(sp.raxml, sp.info.df, by="label")

sp <- ggtree(sp.tree,layout="circular") #+ geom_tiplab(aes(label=anno))
sp

p2 <- sp %>% collapse(node=671) + 
  geom_point2(aes(subset=(node==671)), shape=21, size=5, fill='green')

p2

```



























#FIN.